### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by boristsr** [master-technology/AssetManagerStudio#12]
Heya, great work on this! Really promising. Just throwing some feature ideas out, I couldn't see them listed anywhere, sorry if they are already there:

## Asset Usage Credit List.
I always try and credit what assets I've used, and I wish the EGL, or any launcher would simply append {Asset Name, Link} to an AssetsCredit.txt or something in the base project folder when an asset pack is installed. It'd make it easier to gather later

## Queuing downloads
It seems the install and downloads get greyed out when installing an asset, It'd be nice if i could queue 3-4 assets to install at a time.

**Comment by PeterAndPaul777** [comment]
I thought the same thing on download queue

**Comment by kryokil** [comment]
Cool bit of soft. I havent figured out how to add multiple projects if they are located on different drives. Is this already implemented or could this be added? Thank you and looking forward to more features

**Comment by NathanaelA** [comment]
1. Internally is does support a download queue, but the UI hasn't been updated yet.     
2. To support multiple places for projects you can use `parent_directory_a|parent_directory_b|parent_directory_c|...`   use the "Pipe" character between each path to a primary directory.

**Comment by kryokil** [comment]
works perfectly, thank you so much

**Comment by NathanaelA** [comment]
@boristsr - The next version (0.0.17) will now have a AssetsCredits.txt file it will generate for any projects created from Assets, or any assets put into a project and it will look like this.
![image](https://github.com/master-technology/AssetManagerStudio/assets/850871/06e2027e-6246-4f27-972f-037a1d5f9db3)

Title, Developer, AssetId, URL to asset on store.

In addition the next version (0.0.17) will also have a much better and revamped queued download system, and the greying out will only occur on the item being downloaded...

**Comment by boristsr** [comment]
Awesome! Amazing work! Thanks.
