### ISSUE TITLE
[Bug] Can't install Unreal Engine to my D: drive

### ISSUE THREAD

**Issue by randomperson189** [master-technology/AssetManagerStudio#16]
![image](https://github.com/master-technology/AssetManagerStudio/assets/32617562/e97e01cc-ee13-4df1-be29-612dc9f9c142)

Whenever I try to install Unreal Engine to my D: drive, it gives me this error for some reason
![image](https://github.com/master-technology/AssetManagerStudio/assets/32617562/157cbeb1-2614-4e04-88af-294d793f9f01)
My D: drive has over 100GB free so it should install fine. It's probably trying to install it to my C: drive which I don't want it to

 This issue never occurs when installing Unreal via the Epic Games Launcher

**Comment by NathanaelA** [comment]
Well that is interesting, I'll take a look at the code to see why it would be checking drive C instead of D, as it should be using D since that is where you pointed it to.   Thanks for the report.

**Comment by NathanaelA** [comment]
I've tested this with a second drive on my Virtual Machine and it worked correctly.   So I added more logging to the disk free space, if you can run v0.0.17, try installing, and then under the "Help" menu click the "Save Logs" and attach them, this might give me a clue why it isn't working on your machine...

**Comment by randomperson189** [comment]
[Log-0.txt](https://github.com/master-technology/AssetManagerStudio/files/12303405/Log-0.txt)
Ok so the error stopped showing when I deleted my Unreal Vault folder which was in my "C:\Users\User\Documents" folder but when I try downloading again, it just doesn't do anything.

Update. It seems the issue is that my Unreal Vault folder keeps being created in my documents even though I set it to "D:\Epic Games\VaultCache" in the settings. I fixed the issue by moving the Unreal Vault folder to D:\Epic Games and then renamed it to VaultCache

It now downloads properly, so I guess the issue can be fixed by creating the vault folder at where it's specified in the settings
![image](https://github.com/master-technology/AssetManagerStudio/assets/32617562/509cff30-4100-4abe-bd2b-36175939ef30)

**Comment by NathanaelA** [comment]
Ah, yeah, I think by default the code assumes if it can't find any vault's it then creates it in your documents folder.  So then later in the app it does find the default even though you overrode it in settings.     One update that I just did in 0.17 was it now uses the last vault path that exists as the official path, I guess I should now "auto" create the last path if it doesn't exist where I was just ignoring any path that doesn't exist.   Thanks for the find and debugging, that is very helpful!

**Comment by NathanaelA** [comment]
The next version (0.0.18) will auto-create the last manual vault path you put in, if it doesn't exist so that the downloads will go their.
