### ISSUE TITLE
[Feature Request] Allow the portable version to store files in its folder

### ISSUE THREAD

**Issue by Ares9323** [master-technology/AssetManagerStudio#18]
Hello,
I hope this message finds you well. I've been an avid user of the Unreal Marketplace and your remarkable tool. I'd like to propose a feature that could enhance the user experience.
Currently, when I need to download assets from the Unreal Marketplace using different company accounts, I find it cumbersome to switch back and forth between accounts.

My suggestion is to provide an option to store the "asset-manager-studio" folder within the same directory as the .exe file (Instead of AppData/Roaming). 
This adjustment would enable users like me to effortlessly manage multiple accounts. By keeping the accounts logged in simultaneously, it would significantly streamline the workflow and eliminate the need for constant switching.

In the past, I relied on third-party solutions like TcNo Account Switcher to address this challenge. Unfortunately, I still encountered issues with being frequently logged out, which disrupted my workflow.

I want to express my gratitude for your exceptional tool and the positive impact it has had on my work.
I believe this feature enhancement could further elevate its utility (at least for me).

Thank you for considering my request, looking forward to your response and continued success.

Marco

**Comment by NathanaelA** [comment]
Great idea, I'll look into the feasibility of it.

**Comment by NathanaelA** [comment]
The next version will let you:

   It will look in the current working directory for an `.AMS_DATA` folder and use it, then it will check the command line for a `-DATADIR <path>`, and finally fall back to the default location.

So If you wanted to have two users you could do this a couple different ways 
- `asset-manager-studio -DATADIR C:\unreal\user_a` or on linux ( asset-manager-studio -DATADIR ~/unreal/user_a )
- Or you can create & change to your "user_a" folder do a mkdir ".AMS_DATA" then C:\program~1\asset....\asset-manager-studio) and you don't have to use a CLI command then.   By running it from this folder, it will auto-detect the .AMS_DATA folder and use it all automatically.
- Or finally you can create a shortcut that sets the working directory to the `.AMS_DATA` folder (or the parent folder that contains the `.AMS_DATA` folder) and again it will auto-detect the `.AMS_DATA` folder.

So several ways to allow multiple users data sets.   The simplest imho is just creating two different .AMS_DATA folders in two locations and starting the application up.    

Please note, you do NOT need to have the executable in the same directory, and you can use either the installed or standalone app.   You just need to run the app (or have the current working directory in shortcut) in the location of your .AMS_DATA folder.  

Let me know if this meets all your needs.

**Comment by Ares9323** [comment]
> Please note, you do NOT need to have the executable in the same directory, and you can use either the installed or standalone app. You just need to run the app (or have the current working directory in shortcut) in the location of your .AMS_DATA folder.
> 
> Let me know if this meets all your needs.

Hi! Thanks for the update!
This is certainly better than what I suggested, I was just trying to "keep it simple", I was ok with "having multiple .exe files" just because it's pretty lightweight and I suggested to store files in the .exe folder because it's what other portable software do, your implementation is definitely more versatile!

I'll try it and I'll let you know!
Thank you again!

**Comment by NathanaelA** [comment]
Adding this wasn't that hard, and on Windows the Standalone version doesn't like using the CLI, so I honestly am seriously considering dropping it on windows unless I can figure out why as this causes confusion when people try to use the CLI and it doesn't work...

**Comment by Ares9323** [comment]
Windows often has issues with the terminal if the environmental variables are not set in the way he wants, I've made a tool to open all kinds of 3D files with Blender and I still remember the struggle to make it work...

Maybe I'm biased, but I always prefer the portable version to the installed one, I don't think that keeping only one version would be an issue for other users.

I've tried the new version this morning with 3 different accounts and it seems to work as it should, it would be good to be able to open múltiple instances at the same time but it's not a big deal! 
Thank you so much!

**Comment by NathanaelA** [comment]
The issue with windows is whatever Electron uses for the wrapper doesn't seem to be forwarding the CLI ARGS into the program, so it basically starts up w/o any of the users arguments...    In addition the portable versions are about 1-4 seconds slower starting up depending on the machine/hd, I love speed...

It is on my todo list to try and trace down exactly how it makes the portable exe and see if I can fix the startup code...

> I've tried the new version this morning with 3 different accounts and it seems to work as it should, it would be good to be able to open múltiple instances at the same time but it's not a big deal!

Good idea,  I can detect it using a local .AMS_DATA folder allow multiple instances in that case.     I'll fix this for the next version.
