### ISSUE TITLE
[Bug] Unreal Tip of the Day can't go past page 58

### ISSUE THREAD

**Issue by randomperson189** [master-technology/AssetManagerStudio#21]
When you keep clicking next in the Unreal Tip of the Day window, it can't go past page 58, instead it goes back to page 56 for some reason, the only way to access page 59-64 is if you go backwards from page 1

**Comment by NathanaelA** [comment]
Interesting bug, I can duplicate it also.   I'll get it fixed for the next version.  Thanks!

**Comment by NathanaelA** [comment]
Fixed in v0.0.19
