### ISSUE TITLE
Epic Login no longer works properly.

### ISSUE THREAD

**Issue by ThePixelDiffusionPirate** [master-technology/AssetManagerStudio#27]
(Windows 11)

After updating to 0.0.19, the login no longer works.

After entering the data, a window opens that shows me the settings of my Epic account, but the program still says "logged out." A complete reinstallation did not help.

**Comment by WeirdScienceX** [comment]
I can confirm the same issue

**Comment by NathanaelA** [comment]
Sorry was travelling -- v.0.0.19 was supposed to fix login issue, because Epic changed thing that broke the earlier version.   You can retry v0.0.18 if you want just by re-downloading it.      All the old versions are still downloadable:

v0.0.18 - https://assetmanager.studio/dl/0.0.18/asset-manager-studio%200.0.18.exe   [windows standalone]

Can one of you try this and tell me if v0.0.18 still works for you?

**Comment by mjs1994** [comment]
> Sorry was travelling -- v.0.0.19 was supposed to fix login issue, because Epic changed thing that broke the earlier version. You can retry v0.0.18 if you want just by re-downloading it. All the old versions are still downloadable:
> 
> v0.0.18 - https://assetmanager.studio/dl/0.0.18/asset-manager-studio%200.0.18.exe [windows standalone]
> 
> Can one of you try this and tell me if v0.0.18 still works for you?

I'm having the same issue and tried 0.0.18 and the login button is greyed out entirely.

Thanks!

**Comment by WeirdScienceX** [comment]
> Sorry was travelling -- v.0.0.19 was supposed to fix login issue, because Epic changed thing that broke the earlier version. You can retry v0.0.18 if you want just by re-downloading it. All the old versions are still downloadable:
> 
> v0.0.18 - https://assetmanager.studio/dl/0.0.18/asset-manager-studio%200.0.18.exe [windows standalone]
> 
> Can one of you try this and tell me if v0.0.18 still works for you?

I tried 0.0.18 also and the login button is greyed out

**Comment by NathanaelA** [comment]
I'm uploading v0.0.20 right now, I believe the changes I did in .19 weren't enough to fix the login for everyone.  But the changes in .20 should fix it for everything.
