### ISSUE TITLE
Epic not logging in

### ISSUE THREAD

**Issue by UnsignedCoder** [master-technology/AssetManagerStudio#28]
When i log in to epic games it logs in but still shows logged out on the title bar even though it is clearly logged in. I am using version 0.0.20. I've tried reinstalling and still no progress on it

**Comment by SireNiklas** [comment]
Same issue here.

**Comment by NathanaelA** [comment]
Does it only show logged out, but still work, or are you seeing that it is acting like it is logged out also?

**Comment by SireNiklas** [comment]
Logged out entirely. I can't get my assets, and it states logged out at the top, clicking login doesn't do anything to fix it either.


-------- Original message --------
From: Nathanael Anderson ***@***.***>
Date: 1/19/24 2:58 PM (GMT-06:00)
To: master-technology/AssetManagerStudio ***@***.***>
Cc: Nicholas ***@***.***>, Comment ***@***.***>
Subject: Re: [master-technology/AssetManagerStudio] Epic not logging in (Issue #28)


Does it only show logged out, but still work, or are you seeing that it is acting like it is logged out also?

**Comment by NathanaelA** [comment]
1. Windows or Linux version?
2. Can one of you try manually deleting the data directory and then try starting the application?  
- Windows: https://github.com/master-technology/AssetManagerStudio/wiki/Notes-Windows-OS
- Linux: https://github.com/master-technology/AssetManagerStudio/wiki/Notes-Linux-OS

**Comment by UnsignedCoder** [comment]
I'm using windows 23H2 
I already tried deleting all associated files with the app and logging in again but i still had the same problem. I even tried other sign in options like using google to sign in instead of typing my epic email and password directly but no improvement. I didn't have this issue with version 0.0.19 but there's no way to redownload older versions of the app so i can't test it to be sure

**Comment by NathanaelA** [comment]
You can redownload any version, they are all on the site.  So if you wanted to grab v0.0.19 you can grab it from here https://assetmanager.studio/dl/0.0.19/asset-manager-studio 0.0.19.exe for the portable windows version.   You just need to replace the version numbers to point to any specific version you want.   

However the login code on v0.0.19 is much more strict and would fail if v0.0.20 is failing...

Good news is I have been able to duplicate the issue -- so I'm looking into it and hopefully will have a new release soon...

**Comment by NathanaelA** [comment]
This should be fixed in v0.0.21

**Comment by NathanaelA** [comment]
Actually after a lot more testing today, I found a corner case that might require you to restart the program if using MFA .   Which is now fully fixed in v0.0.22 -- in addition I had time to test one of my ideas for better login experience and added that extra code that should be able to detect earlier in the login flow that the login is valid.

**Comment by UnsignedCoder** [comment]
Thank you very much. Now back to never using epic launcher
