### ISSUE TITLE
[BUG] Unable to Download Unreal Engine versions

### ISSUE THREAD

**Issue by reaply** [master-technology/AssetManagerStudio#39]
Unexpectedly, my Unreal Engine 5.3.2 directory got deleted and I'm unaware as to how or why. Upon trying to download 5.3.2 (or anything or version), I am getting a queuing status and then fails immediately. Upon looking through terminal, there seems to be an EPIC API change or failure that is blocking it from being downloaded.

 `[EpicAPI] getLinuxUnrealVersions: 401 {"message":"epic.common.sso.missing_bearer_token"}
No Asset Manager Studio update needed.
[EpicAPI] getLinuxUnrealVersions: 401 {"message":"epic.common.sso.missing_bearer_token"}
false
`

![image](https://github.com/master-technology/AssetManagerStudio/assets/7589359/2aab730f-eb01-4e05-b2bb-0d5ad62906d5)

**Comment by reaply** [comment]
Solution:

Navigate to: `/home/[user]/.config/asset-manager-studio/` and rename `assetmanagerstudio.sqlite` to `assetmanagerstudioOld.sqlite` to force asset manager to generate a new sqlite database and to forcefully login to EPIC to generate **NEW** API tokens, as it seems the ones I had were old.

Please add a functionality to sign out of your EPIC account and to login again so that new API tokens can be achieved without this manual process and so users won't think that it's broken. Asset Manager is great!

**Comment by NathanaelA** [comment]
Strange, it should have detected that the Token was outdated and forced a re-login.    I'll have to double check the code...

You can also run it with the command line `--deletedata` to purge your cache & the sqlite file...

I'm glad you were able to get it working again!

**Comment by NathanaelA** [comment]
I have been able to duplicate this issue, it is on my radar to fix...  :grinning:

**Comment by NathanaelA** [comment]
Cleaning issues -- I believe this was fixed in one of the earlier version when I was dealing with a lot of login issues, I now even support the refresh token properly...
