### ISSUE TITLE
Feature Sort by Updated

### ISSUE THREAD

**Issue by imtrobin** [master-technology/AssetManagerStudio#47]
Hi, I like to know if its possible to sort by assets that are updated. There are two kinds

1. In original launcher, the Add to Project will show the world "Updated"

2. Some assets are updated by they don't show any indication. When I download the asset again, the vault will have a new version number, e.g. XXXXV2, XXXXXV3 etc.

Able to detect those?

Also, I sort by Date Modified, my vault now is showing 5.5.0

**Comment by NathanaelA** [comment]
I'm working on reworking this code, so right now no the updated date isn't tracked properly/broken ---  but in the future yes.

Not sure what you mean by it shows "5.5.0" when you sort by Date Modified, it should have a date.

**Comment by imtrobin** [comment]
![Asset Manager Studio-2024-07-31 23_49_29](https://github.com/user-attachments/assets/e50a1163-aadc-45a9-87a2-ff64251e877e)

**Comment by NathanaelA** [comment]
Ah, yeah that is the expected behavior -- those vault items are were modified on disk later than the others.    If you click on one of them you will see the modified date.         Unreal 5.5 assets would be newer then most Unreal 5.2.   

Is there some other behavior you are looking for?

**Comment by imtrobin** [comment]
What does the modified on disk mean? Did the asset updated or the asset json changed? This is related to the other issue cos the assets show files modified even thought I did not update them. The unreal behavior only reads, it does not touch the files on disk.

https://github.com/master-technology/AssetManagerStudio/issues/48

**Comment by NathanaelA** [comment]
If my internal modified date (for sorting) is being updated by my creating the json file, that is a bug -- I'll take a look at it.   

The modified date should be the last time the asset itself was updated and should be using the date from the actual asset/plugin configuration file, not my `vault.json` file.    AMS should NOT be writing to any of the actual asset files as those are accessed as read only.

**Comment by imtrobin** [comment]
There seems to be a bug, as you see in my screenshot, there ButterFly Particles shows 5.2.0, but I did download a 5.4 version recently.

**Comment by NathanaelA** [comment]
As of v0.0.26 - Vault now has a "Updatable" in the type search.

![image](https://github.com/user-attachments/assets/9c94c8de-66a6-433e-96ce-4d38018b4923)
