### ISSUE TITLE
[Feature Request] Ability to add multiple project paths

### ISSUE THREAD

**Issue by RTerofer** [master-technology/AssetManagerStudio#51]
Is it possible to add multiple base project paths ?

**Comment by NathanaelA** [comment]
This is already supported, just do <path1> | <path2> | <path3>  separate them by a "|"

**Comment by RajeshTerofer** [comment]
Hi Nathanael, It doesnt work for me. It's throwing an error or either picking up only one path. I might be doing something wrong. Could you provide me an example for this ?

**Comment by NathanaelA** [comment]
https://github.com/master-technology/AssetManagerStudio/wiki/Screen-Settings has more details.
