### ISSUE TITLE
Fab plugin

### ISSUE THREAD

**Issue by Psijic** [master-technology/AssetManagerStudio#52]
Epics didn't provide direct link to download Fab plugin - is there a way to integrate it for Linux?

**Comment by bringrainfire** [comment]
If you build the engine from source (5.5 or ue5-main), they will have the fab plugin ready to go. But be aware that it only works for content/asset only plugins. Code plugins won't work until it's addressed and fixed. And the neither asset manager studio nor the epic asset manager can see assets purchased through fab.

**Comment by Psijic** [comment]
Nice to hear, most of the stuff already implemented. But you saying, there's no way to get new code plugins bought via Fab even for Windows users? That sounds interesting.

**Comment by bringrainfire** [comment]
oh, don't know about windows. I was talking about within linux. Right now the only workaround for getting code plugins on linux is to setup a fake engine using steam's proton or through wine to run the epic launcher.

**Comment by Psijic** [comment]
> oh, don't know about windows. I was talking about within linux. Right now the only workaround for getting code plugins on linux is to setup a fake engine using steam's proton or through wine to run the epic launcher.

You mean, all the plugins work properly on Linux without recompilation?

**Comment by NathanaelA** [comment]
No they have to be recompiled, I believe he is using the other way around to get plugins downloaded, once it is d/l you can recompile it...

**Comment by Psijic** [comment]
So, the plugins shipped with the source code then. I heard, many proprietary are not. But if you have an access to S/C, possible you can build it without downloading the libs. Just need to dig Github for the sources.

**Comment by NathanaelA** [comment]
Virtually all plugins are shipped with sources.   So far in my experience it is pretty rare to find one that doesn't have source.  Normally large companies (Like Meta) can get exceptions, but all the smaller companies I think are required to ship sources.

**Comment by NathanaelA** [comment]
Just to let you know, Fab support is coming.   I've got all the URL's documents, just need to code and test things.   I've already got pieces implemented, but it is a bit slow because AMS is currently a very low priority do to trying to find a job (Company downsized) and/or more contract work...

**Comment by NathanaelA** [comment]
Fab is finally supported in v0.0.26 lots of fixes and lots of cleanups.   Feel free to kick the tires!

**Comment by bringrainfire** [comment]
I've been using over the holidays and so far it's working perfectly. I can clean up the wine install of the epic launcher now. Thank you for building a great piece of software!
