### ISSUE TITLE
[Feature request] Show purchased assets not appearing in Fab 

### ISSUE THREAD

**Issue by JetScalawag** [master-technology/AssetManagerStudio#58]
Please include the ability to include purchased assets that don't appear in Fab, perhaps have a filter for these as well ("Not in FAB")

**Comment by NathanaelA** [comment]
I've added a "Third Party" Type to the Vault screen in the next version

**Comment by JetScalawag** [comment]
I'm not entirely sure if we're on the same page regarding this. This is in reference to assets like the one below, which have been abandoned by their author. (I actually have a separate "Third Party" request haha.)

![{D7B11200-803D-4EE8-B1C4-35AAFBC1A50D}](https://github.com/user-attachments/assets/e28e27de-3bfa-4805-9105-84b5a5b6d609)

**Comment by JetScalawag** [comment]
Another example: 

![{D25B0C42-B801-4A04-BCFF-A6EB9DB11550}](https://github.com/user-attachments/assets/39592b1b-7eb8-42c3-aa20-a9d5a451631c)
